<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Market Data Report</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1f2937; font-size: 11px; margin: 0; padding: 20px; }
        .header { border-bottom: 2px solid #0d9488; padding-bottom: 10px; margin-bottom: 20px; text-align: center; }
        .header h1 { margin: 0; font-size: 24px; color: #0f766e; text-transform: uppercase; letter-spacing: 1px; }
        .meta { color: #6b7280; font-size: 10px; margin-top: 5px; }
        
        .filters { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px; margin-bottom: 20px; width: 100%; box-sizing: border-box; }
        .filters table { width: 100%; border: none; }
        .filters td { padding: 4px 8px; border: none; font-size: 11px; color: #374151; }
        .filters strong { color: #111827; }

        .data-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .data-table th, .data-table td { border: 1px solid #e5e7eb; padding: 8px 10px; text-align: left; }
        .data-table th { background-color: #f1f5f9; color: #475569; font-weight: bold; text-transform: uppercase; font-size: 10px; letter-spacing: 0.5px; }
        .data-table tbody tr:nth-child(even) { background-color: #f8fafc; }
        .data-table td.price { font-weight: bold; color: #0d9488; }
        
        .footer { position: fixed; bottom: 0; left: 0; right: 0; text-align: center; font-size: 9px; color: #9ca3af; padding-top: 10px; border-top: 1px solid #e5e7eb; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Market Intelligence Data Report</h1>
        <div class="meta">Generated by Market Databank &bull; {{ $generatedAt->format('F d, Y \a\t H:i') }}</div>
    </div>

    <div class="filters">
        <table>
            <tr>
                <td><strong>Category:</strong> {{ $filters['category'] ?: 'All Categories' }}</td>
                <td><strong>Region:</strong> {{ $filters['region'] ?: 'All Regions' }}</td>
                <td><strong>Year:</strong> {{ $filters['year'] ?: 'All Years' }}</td>
                <td><strong>Total Records:</strong> {{ $rows->count() }}</td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th>Product / Asset</th>
                <th>Category</th>
                <th>Region</th>
                <th>Price (₹)</th>
                <th>Demand (1-5)</th>
                <th>Supply (1-5)</th>
                <th>Date Logged</th>
                <th>Primary Source</th>
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
                <tr>
                    <td>{{ $row->product->name ?? '-' }}</td>
                    <td>{{ $row->category->name ?? '-' }}</td>
                    <td>{{ $row->location->state ?? '-' }}</td>
                    <td class="price">{{ number_format((float) $row->price, 2) }}</td>
                    <td>{{ $row->demand_level }}</td>
                    <td>{{ $row->supply_level }}</td>
                    <td>{{ optional($row->data_date)->format('Y-m-d') }}</td>
                    <td>{{ $row->source }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Confidential & Proprietary &copy; {{ date('Y') }} Market Databank Platform. All rights reserved.
    </div>
</body>
</html>
